name: "Build & Deploy"
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: "Build And Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install NodeJs"
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "Build"
        run: |
          npm install
          npm run build

      - name: "Deploy"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "dist"
          target: "/root/workspace/"
