name: "learn github actions"
on:
  push:
    branches:
      - qa
      - master

jobs:
  test-one:
    name: 'query github info'
    runs-on: ubuntu-latest
    steps:
      - name: "time stamp"
        id: "timestamp"
        run: |
          echo "Time Stamp start"
          echo ":set-output name=random::$(echo "${RANDOM}")"
      - name: 'end step'
        env:
          time: ${{ steps.timestamp.outputs.time }}
          random: ${{ steps.timestamp.outputs.random }}
        run: |
          echo "release-${time}-${random}"
          echo "random-${random}"

