name: "learn github actions"
on:
  push:
    branches:
      - master
      - release**
      - qa**

env:
  SERVER: production

jobs:
  job-one:
    name: 'query github info'
    runs-on: ubuntu-latest
    steps:
      - name: "declare variable"
        id: "declare_variable"
        run: |
          echo "::set-output name=time::$(echo `date --date="now +8 hours" +%Y%m%d%H%M%S`)"
          echo "::set-output name=random::$(echo "${RANDOM}")"
      - name: 'declare environment variable'
        env:
          time: ${{ steps.declare_variable.outputs.time }}
          random: ${{ steps.declare_variable.outputs.random }}
        run: |
          echo "release-${time}-${random}"
          echo "random-${random}"

