name: "learn github actions"
on:
  push:
    branches:
      - qa
      - master

env:
  SERVER: 'production'

jobs:
  test-one:
    name: 'test environment'
    runs-on: ubuntu-latest
    steps:
      - name: 'first-step'
        env:
          ref: ${{ github.ref }}
          ref_name: ${{ github.ref_name }}
          ref_type: ${{ github.ref_type }}
          info: ${{ toJSON(github) }}
        run: |
          echo "${ref}"
          echo "========================"
          echo "${ref_name}"
          echo "========================"
          echo "${ref_type}"
          echo "========================"
          echo "${info}"
