name: "learn github actions"
on:
  push:
    branches:
      - master
      - release**
      - qa**

env:
  SERVER_NAME: production

jobs:
  job-one:
    name: 'query github info'
    runs-on: ubuntu-latest
    steps:
      - name: "declare variable"
        env:
          commit_message: ${{ env.SERVER_NAME }} ${{ github.event.head_commit.message}}
        run: |
          echo "${commit_message}"
