name: "learn github actions"
on:
  push:
    branches:
      - qa
      - master

jobs:
  test-one:
    name: 'query github info'
    runs-on: ubuntu-latest
    steps:
      - name: 'first-step'
        env:
          ref: ${{ github.ref }}
          ref_name: ${{ github.ref_name }}
          ref_type: ${{ github.ref_type }}
          user_name: ${{ github.event.pusher.name }}
          user_email: ${{ github.event.pusher.email }}
          commit_message: ${{ github.event.head_commit.message }}
        run: |
          echo "ref: ${ref}"
          echo "========================"
          echo "ref_name: ${ref_name}"
          echo "========================"
          echo "ref_branch: ${ref_type}"
          echo "========================"
          echo "userName: ${user_name}"
          echo "========================"
          echo "userEmail: ${user_email}"
          echo "========================"
          echo "commitMessage: ${commit_message}"
